---
# yumの実行
- name: yum -y update
  yum: name=* state=latest

- name: yum install epel-repease
  yum: name=epel-release state=installed
  
- name: add remi-repo repository
  command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo

- name: YUMインストール(全体)
  yum: name={{item}} state=latest
  with_items:
    - gcc
    - zlib-devel
    - openssl-devel
    - mariadb
    - mariadb-server
    - libffi-devel
    - libxml2-devel
    - libxslt-devel
    - httpd-devel
    - curl-devel
    - apr-devel
    - apr-util-devel
    - readline-devel
    - ImageMagick
    - ImageMagick-devel
    - git
    - sqlite-devel
    - epel-release
    - nodejs
    - npm
    - autoconf
