---
- name: install php 7.3
  yum: name={{ item }} enablerepo=remi,remi-php73 state=installed
  with_items:
    - php
    - php-devel
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pdo
    - php-xml
    - php-zip

- name: deploy php.ini
  template:
    src: php.ini.j2
    dest: /etc/php.ini
