---
- name: install php 7.3
  yum: name={{ item }} enablerepo=remi,remi-php73 state=installed
  with_items:
    - php
    - php-devel
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pdo
    - php-xml
    - php-zip
    - php-pecl-xdebug

- name: deploy php.ini
  template:
    src: php.ini.j2
    dest: /etc/php.ini

- name: deploy 
  template:
    src: 15-xdebug.ini.j2
    dest: /etc/php.d/15-xdebug.ini

- name: check composer
  stat: path=/usr/local/bin/composer
  register: composer_bin
  tags: composer

- block:
  - name: download composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer

  - name: install composer
    shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin

  - name: install composer
    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer

  - name: make composer executable
    file:
      path: /usr/local/bin/composer
      mode: a+x
      state: file
  when: not composer_bin.stat.exists
  tags: composer
